<a href="https://colab.research.google.com/github/kayleeoneill/Probability_Statistics/blob/main/Kayleeoneill_Stats_2023_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [24]:
for i in range(100):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [25]:
#a range from 0-99

In [26]:
for i in range(5,8):
    print(i)

5
6
7


In [27]:
for i in range(3):
    print( "Test Number: " , i )

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [28]:
def square(x):
    return x**2

In [29]:
square(5)

25

In [30]:
square(square(2))

16

In [31]:
square(square(square(2)))


256

In [32]:
square(123456)

15241383936

In [33]:
square(square(5))

625

In [34]:
def add_two(x):
    return x+2

In [35]:
add_two(5)

7

In [36]:
square(add_two(5))

49

In [109]:
#mkaing a continuous function 

### Logical Branching

In [37]:
choice = "apple"

In [110]:
#define apple

In [38]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


In [111]:
#an output

In [39]:
choice = "orange"

In [40]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [41]:
choice = "apple"

In [42]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


In [112]:
#if then statements

### User Input

In [43]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): apple


In [113]:
#allows the users to input

In [44]:
choice

'apple'

In [45]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You choose apples.


#### Coins

In [51]:
np.random.random()

0.5546651819389492

In [53]:
np.random.random() > 0.5

False

In [114]:
#allows for a 50% chance 

In [54]:
def flip_coin():
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

In [115]:
# lets you flip a virtual coin 

In [55]:
flip_coin()

Tails


### Graphics Output

In [56]:
from IPython.core.display import display, HTML

In [57]:
display(HTML('<h1>Hello, world!</h1>'))

In [116]:
#outputs

In [58]:
def coin():
  return np.random.randint(2)

In [59]:
coin()

1

In [60]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">'))

In [61]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

In [62]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [117]:
#lets you show a visual for the virtual coin flip

In [63]:
show_img(heads)

In [64]:
show_img(tails)

In [65]:
def flip_coin():

    if coin():
        show_img(heads)
    else:
        show_img(tails)

In [66]:
flip_coin()

In [67]:
for i in range(5):
    flip_coin()

In [119]:
#lets you do multiple flips at once

In [68]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [69]:
def shuffle(x):
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [70]:
a = np.arange(52)

In [120]:
#shows an array of 52 numbers

In [71]:
shuffle(a)

array([ 3, 23, 36, 26, 21, 27, 35, 42,  0, 32, 34, 31, 29, 24, 19, 13, 45,
       51, 16, 11,  2,  9, 47, 17, 33, 39, 18, 40, 50,  5,  6,  4, 28, 46,
        7, 37,  8, 15,  1, 41, 14, 38, 10, 20, 22, 43, 12, 48, 49, 44, 30,
       25])

In [121]:
#randomizes the numbers

In [72]:
np.random.permutation(52)

array([49, 22, 35, 42, 24, 51, 44, 14, 32, 23, 10, 37,  6, 38, 27, 12,  5,
       18, 31, 46,  1,  9, 19, 30, 41, 13,  3,  4,  2, 45, 36, 43, 11, 33,
       29, 28, 26, 34, 40,  8, 48, 21,  7, 16,  0, 20, 50, 25, 15, 47, 39,
       17])

### Speed Test

In [73]:
%%timeit
shuffle(a)

202 µs ± 56.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [74]:
%%timeit
np.random.permutation(52)

3.42 µs ± 179 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [122]:
#shuffling the cards for a random amount

In [75]:
import numpy as np

In [76]:
np.random.permutation(52)

array([17, 40, 41, 39,  9, 29, 11, 25, 24, 27,  5,  1, 51, 31, 12, 46,  2,
       19, 36, 37, 28,  4,  0, 14, 10,  7, 20, 18, 45,  3, 42,  6, 33, 35,
       48, 30, 44, 38, 26, 15, 49, 50, 16, 32, 34, 22, 23, 13,  8, 47, 21,
       43])

In [77]:
cards = np.random.permutation(52)

In [78]:
cards

array([14, 43,  6, 28,  0, 45, 32, 12, 20, 13, 22, 19, 35,  2, 27, 26, 18,
       48, 11,  4, 15, 49, 50, 46,  5,  3, 16, 33, 31,  8,  7, 34, 47, 17,
        1, 37, 10, 42, 41,  9, 30, 44, 29, 21, 23, 51, 38, 36, 25, 39, 40,
       24])

In [123]:
#defining cards as the random array

In [79]:
cards[0]

14

In [124]:
#the first card in the deck

In [80]:
cards[1]

43

In [81]:
cards[2]

6

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [82]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [125]:
#shaping the array to 4 suits of 13 cards

In [83]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [126]:
#making the numbers the same in each suit

In [84]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [85]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [127]:
#naming the suits and giving the cards names instead of numbers

In [86]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [87]:
card_name(0)

'Ace of Clubs'

In [128]:
#give a specific card a specifc name

In [88]:
card_name(51)

'King of Diamonds'

In [89]:
cards = np.random.permutation(52)

In [90]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [91]:
top_of_deck, second_card_in_deck, last_card_in_deck

('Four of Hearts', 'Ace of Hearts', 'Seven of Diamonds')

In [92]:
for i in range(5):
    print(card_name(cards[i]))

Four of Hearts
Ace of Hearts
Six of Clubs
King of Hearts
Jack of Hearts


In [93]:
for i in range(15):
    print(card_name(cards[i]))

Four of Hearts
Ace of Hearts
Six of Clubs
King of Hearts
Jack of Hearts
Seven of Clubs
Jack of Spades
Nine of Hearts
Three of Hearts
Six of Spades
Eight of Clubs
Five of Hearts
King of Clubs
Seven of Hearts
Two of Clubs


In [129]:
#randomly generating 15 cards

https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [94]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [130]:
#inserting images for the cards 

In [95]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [96]:
i = np.random.randint(4)
j = np.random.randint(13)

In [97]:
i,j

(0, 10)

In [98]:
suit[i]

'k'

In [99]:
card[j]

'j'

In [100]:
from IPython.core.display import display, HTML

In [101]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [102]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [103]:
show_img(img)

In [131]:
#using images to show the cards that were randomly generated

In [104]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [105]:
card_image(3)

'k4'

In [106]:
img = card_url_head + card_image(3) + card_url_tail

In [107]:
show_img(img)

In [108]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)